table DATA
	lineageTag: a3155712-487e-4499-a76c-12483f46714c

	column name
		dataType: string
		lineageTag: b665861e-70f6-41ad-9e9e-7a284c43be17
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column last_q_ledger
		dataType: string
		lineageTag: 4ee8afd8-2a26-4691-ba0d-27e6889bee6c
		summarizeBy: none
		sourceColumn: last_q_ledger

		annotation SummarizationSetBy = Automatic

	column is_decisions_submitted
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3589488b-71d8-49e2-b16a-0cd76928721e
		summarizeBy: none
		sourceColumn: is_decisions_submitted

		annotation SummarizationSetBy = Automatic

	column market_share
		dataType: double
		lineageTag: 8ddc75cd-f9a3-4d5f-9ff3-aac906d56b6d
		summarizeBy: sum
		sourceColumn: market_share

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Attribute
		dataType: string
		lineageTag: 8f09dc82-7327-49ad-9f5a-233186aadd8e
		summarizeBy: none
		sourceColumn: Attribute

		annotation SummarizationSetBy = Automatic

	column Value
		dataType: double
		lineageTag: 93b4207d-da92-40a7-817c-a9ae0f3e0f01
		summarizeBy: sum
		sourceColumn: Value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DATA = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("db.abkjmgfazfhhncseybvz.supabase.co", "postgres"),
				  #"Navigation 1" = Source{[Schema = "public", Item = "companies"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(#"Navigation 1",{"name", "cash", "accounts_receivable", "prepaid_amounts", "inventory_units", "fixed_assets_gross", "accumulated_depreciation", "accounts_payable", "credit_line", "bank_loan", "shareholders_equity", "retained_earnings", "comp_display_level", "comp_optics_level", "comp_tracking_level", "comp_processor_level", "brand_equity", "is_frozen", "prev_price", "prev_production_volume", "prev_brand_spend", "prev_capex", "prev_rd_upgrade_fees", "prev_credit_draw", "prev_credit_repay", "prev_loan_draw", "prev_loan_repay", "last_q_ledger", "is_decisions_submitted", "market_share"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"name", "last_q_ledger", "is_decisions_submitted", "market_share"}, "Attribute", "Value")
				in
				  #"Unpivoted Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

